#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 28 12:25:08 2019

@author: ram
"""


""" Cofactors Sources : http://cheminfo.u-strasbg.fr:8080/scPDB/2012/db_search/scpdb_generation_process.jsp, 
http://www.ebi.ac.uk/pdbe/api/doc/pdb.html, 
http://www.ebi.ac.uk/pdbe/api/pdb/compound/cofactors"""


def string_to_list(factor):
    factor = factor.split(',')
    list_cofactor = set()
    for i in factor: 
        list_cofactor.add(i.strip())
    return list_cofactor

def list_to_dict(list_cofactor):
    dict_cofactor = {}
    for i in list_cofactor:
        dict_cofactor[i] = True    
    return dict_cofactor
    
    
    
factor = """
1CM, 2BM, 2MO, 6WO, 6HE, 749, 7HE, A71, A72, A48, AF3, AIO, ALF, AMS, APW, ARS,
AST, AUC, B69, B70, BEF, BEF, BF2, BH1, BPT, BRO, C1O, C2C, CAC, CAD, CAS, CFM,
CFN, CFO, CFQ, CLF, CLP, CM6, CN1, CNB, CNF, CUB, CUM, CUN, CUO, DP4, DRN, DW2,
DWC, EMC, EMT, F3S, FCO, FDC, FEO, FES, FNE, FS1, FS2, FS3, FS4, FSO, HC0, HC1,
HF3, HF5, HGB, HGC, HGI, HO3, IAP, IBZ, IDO, IOD, ISU, IUM, JM1, KYS, KEG, LCP,
LPT, MAC, MAP, MBO, MGF, MGO, MM4, MMC, MNH, MNR, MN5, MN6, MO1, MO2, MO3, MO4,
MO5, MO6, MO7, MOO, MOS, MTD, MW1, MW2, MW3, NA2, NA5, NA6, NAO, NAW, NBF, NCO,
ND4, NFS, NI1, NI2, NI3, NPB, O4M, OC1, OC2, OC3, OC4, OC5, OC6, OC7, OC8, OCL,
OCM, OCN, OCO, OF1, OF2, OF3, PBA, PBC, PBM, PCL, PEU, PHF, PHG, PMB, PPB, REO,
 RHX, RTC, R4A, R6A, SBD, SBL, SBO, SE4, SES, SF3, SF4, SIF, SM2, SM3, SM4, SRB,
 SRD, SUF, T42, TAS, UNK, UNX, V35, V36, V7O, VA1, VO4, WCC, WO4, WO5, XCC, YBT,
 ZO3, 1CP, ACO, B12, BCB, BCL, BPB, BPH, CHL, CL1, CL2, CLA, CLN, CNC, COB, COH,
 COY, CP3, DDH, DEU, DHE, HAS, HCO, HDD, HDM, HEA, HEB, HEC, HEG, HEM, HEO, HES,
 HIF, HNI, MMP, MP1, PC3, PCU, PNI, POR, PP9, SRM, U10, ZEM, ZNH, CO, ACP, ADP,
 AMP, ANP, ATP, H4B, CDP, CMP, COA, CAA, CAO, CTP, FAD, FMN, GDP, GMP, GNP, GTP,
 NAD, NAP, NAI, NDO, NDP, MCA, SCA, UMP, 12P, 15P, 16A, 1LU, 1PE, 1PG, 2HP, 2IB,
 2LU, 2NO, 2PA, 2PE, 2PO, 20S, 3PO, 4CB, 4IP, 4SC, 5IP, 6CT, 9CS, A2G, A6P, AAB,
 AAS, ABA, ABH, ACE, ACN, ACR, ACT, ACY, ADA, AHG, AHR, AI2, ALG, AMV, APB, ARE,
 AZI, B1F, B2A, B2F, B2I, B2V, BCT, BDB, BEM, BEQ, BEZ, BGC, BGL, BJH, BJI, BJP,
 BLE, BLY, BMA, BME, BNO, BNS, BNZ, BO3, BOC, BOG, BOR, BRM, BTB, BUB, BUT, BZB,
 BZO, C8E, CAP, CBM, CBX, CBZ, CCN, CE1, CE8, CE9, CEC, CEF, CEP, CFA, CFT, CH2,
 CH3, CHX, CIT, CKP, CLB, CLD, CLO, CMO, CNN, CO2, CO3, CPS, CRY, CTB, CTT, CVB,
 CXB, CXE, CYA, CYC, CYN, DAO, DDQ, DEP, DFP, DGA, DGG, DIO, DIS, DMS, DOD, DOX,
 DPE, DPO, DTT, DTU, DTV, DUM, EDO, EGC, EGL, EOX, EPE, EPO, ETD, ETF, ETH, ETM,
 ETO, ETP, F09, FAG, FLO, FMT, FOR, FRU, FUC, FX3, G16, G3P, G4S, GAI, GAL, GCM,
 GLA, GLC, GOL, GTE, H01, H02, H2S, HCA, HED, HEX, HEZ, HOA, HOH, HMC, HP3, HPG, 
 HPH, HTO, HYD, I3P, I4P, IAS, IBS, IDR, IDS, IHP, ILG, IOH, IP5, IPA, IPS, JEF,
 KDF, KFG, KO4, KPH, L1P, L2P, L3P, L4P, LAT, LBT, LCO, LDA, LDY, LGV, LI1, LMT,
 M1N, M6D, M6P, MAN, MAS, MAV, MAW, MBT, MCB, MCE, ME2, MES, MG8, MIP, MLR, MMA,
 MNC, MOH, MPA, MPC, MPD, MPO, MPS, MRD, MTO, MVL, MYS, N8E, NAG, NBN, NDG, NET, 
 NGA, NGS, NH2, NH3, NH4, NHE, NHV, NMO, NOY, NO2, NO3, NPY, NS5, NTB, OCT, ODS,
 OET, OHE, OMB, OME, OMO, OTE, OXA, OXN, OXO, OXY, P33, P4C, P6G, PCZ, PDO, PE3,
 PE4, PE5, PE6, PE7, PED, PEG, PEO, PER, PG4, PG5, PG6, PGE, PGR, PGR, PHS, PIM,
 PIN, PLM, PLP, PMP, PNZ, PO2, PO3, PO4, POP, PPK, PPM, PSS, PUT, PVL, QPS, QV4,
 RAF, RUB, SBU, SCC, SCH, SCN, SEO, SFN, SFO, SGN, SIA, SLE, SO2, SO3, SO4, SOH, 
 SOM, SPH, SPM, SPN, SPO, SQU, SUC, SUL, TAM, TAR, TCB, TC4, TFA, THJ, TMA, TME,
 TMN, TPH, TRS, TRT, TSM, UND, UNK, UNX, VXA, WZ1, WZ2, XPE, XYP, YRR, YT3, 20S,
 3MG, 4IP, 9CS, 9MR, A2G, A6P, ACI, ADA, AGL, AHR, AMV, ARE, B4G, BCG, BEM, BGC,
 BMA, CBI, CM5, CTR, CTT, DOM, DPO, EHN, F6P, FRU, FUB, FUC, FX1, FX3, G2I, GAC,
 GAL, GCS, GCU, GLA, GLB, GLC, GLD, GLO, GOL, GOL, GS1, H1M, HMC, HS2, I3P, IDR,
 IDS, IP5, KDA, KDB, KDD, KDE, KDF, KDR, KFG, KO2, LAT, LDY, M6D, M6P, MAB, MAL,
 MAN, MAV, MAW, MMA, MTT, MVL, NAG, NDG, NGA, NHV, NOY, NYT, OBD, OXZ, PAR, QPS,
 QPU, QV4, RAF, SER, SGC, SGN, SIA, SUC, UNF, UNL, WZ1, WZ2, X4S, X5S, XUL, XYL, 
 XYP, XYS, ASC, F43, M43,  MDO, PNS,  0WD, 1DG, 3AA, 3CD, 6V0, 8ID, A3D, AP0,
 CND, DG1, DN4, EAD, ENA, LNC, N01, NA0, NAD, NAE, NAI, NAJ, NAP, NAQ, NAX, NBD,
 NBP, NDC, NDE, NDO, NDP, NHD, NPW, ODP, P1H, PAD, SAD, SAE, SND, TAD, TAP, TDT,
 TXD, TXE, TXP, ZID, 18W, 29P, DPM, 2MD, MCN, MGD, MSS, MTE, MTQ, MTV, PCD, XAX, 
 B12, CNC, COB, COY, 6FA, FA8, FAA, FAB, FAD, FAE, FAO, FAS, FCG, FDA, FED, FSH,
 P5F, RFL, SFD, 1YJ, C2F, FFO, FON, FOZ, THF, THG, THH, 01A, 01K, 0ET, 1C4, 1CV,
 1CZ, 1HA, 1VU, 1XE, 2CP, 2NE, 3CP, 3H9, 3HC, 4CA, 4CO, 8JD, 8Z2, ACO, AMX, BCA,
 BCO, BSJ, BYC, CA3, CA5, CA6, CA8, CAA, CAJ, CAO, CIC, CMC, CMX, CO6, CO8, COA, 
 COD, COF, COO, COT, COW, COZ, DCA, DCC, FAM, FCX, FRE, FYN, GRA, HAX, HMG, HSC, 
 HXC, MCA, MCD, MDE, MLC, MYA, NHM, NHQ, NHW, NMX, OXK, S0N, SCA, SCD, SCO, SDX,
 SOP, T1G, TC6, WCA, YNC, ZOZ, SHT, TP7, TPZ, TXZ, XP8, XP9, 4LS, 4LU, FMN, FNR,
 FNS, IRF, RBF, MQ7, COM, 6HE, 7HE, CCH, COH, DDH, DHE, FDE, FMI, HAS, HDD, HDE,
 HEA, HEB, HEC, HEM, HIF, ISW, MH0, MNH, MNR, PP9, SH0, SRM, ZEM, ZNH, 4AB, 7AP,
 BHS, BIO, H2B, H4B, HBI, WSD, PQQ, BTI, BTN, BYT, DTB, Y7Y, LPA, LPB, 4YP, AT5,
 UQ1, UQ2, UQ5, UQ6, 0HG, 0HH, 1JO, 1JP, 1R4, 3GC, 48T, 5AU, ABY, AHE, ATA, BOB,
 BYG, EPY, ESG, GBI, GBP, GBX, GDN, GDS, GF5, GGC, GIP, GNB, GPR, GPS, GS8, GSB, 
 GSF, GSH, GSM, GSN, GSO, GTB, GTD, GTS, GTX, GTY, GVX, HAG, IBG, ICY, JM2, JM5, 
 JM7, L9X, LEE, LZ6, RGE, TGG, TS5, VWW, ZBF,  LTQ, TTQ, CTQ, 0AF, TOQ, TQQ, TRQ,
 0UM, 0XU, 0Y0, 0Y1, 0Y2, 36A, 37H, 4IK, 62X, 6NR, 76H, 76J, 76K, 76L, 76M, EEM,
 K15, SA8, SAH, SAM, SFG, SMM, SX0, TT8, 1TP, 1U0, 2TP, 5GY, 8EF, 8EL, 8EO, 8FL,
 8PA, D7K, EN0, HTL, M6T, N1T, N3T, R1T, S1T, T5X, T6F, TD6, TD7, TD8, TD9, TDK,
 TDL, TDM, TDP, TDW, THD, THV, THW, THY, TP8, TPP, TPU, TPW, TZD, WWF, MPL, NOP,
 NPL, PDP, PLP, PLR, PMP, PXP, PZP, UAH, 1TY, 2TY, AGQ, G27, HCC, P2Q, P3Q, TPQ, 
 TYQ, TYY, ZN, HOH, SO4, FMN, CA, NAD, SO3, AMP, ADP, FDP, PO4, NAG, CU, NDP, FE,
 NAP, MN, UMP, CO, SF4, MG, CL, UFP, FAD, HG, FDP"""


list_cofactor = string_to_list(factor) # Convertion of cofactor string to list"""
dict_cofactor = list_to_dict(list_cofactor) #"""conversion list to dict where presence will result True"""




